[[redirects]]
from = "/i/u/static/:path*"
to = "https://us-assets.i.posthog.com/static/:splat"
host = "us-assets.i.posthog.com"
status = 200
force = true

[[redirects]]
from = "/i/u/:path*"
to = "https://us.i.posthog.com/:splat"
host = "us.i.posthog.com"
status = 200
force = true

[[redirects]]
from = "/i/u/decide"
to = "https://us.i.posthog.com/decide"
host = "us.i.posthog.com"
status = 200
force = true
